# Site settings
email: greenopalgecko@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Tornado Python
description: Patrick Brandt`s Blog
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Patrick Brandt
profile_img: 
profile: 
social:
  github: archeryprogrammer13

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
